### DISCUSSION TITLE
A small template to setup replication using kvrocks

### DISCUSSION THREAD

**Discussion by uds5501** [apache/kvrocks#1485] [General]
Hey folks, as part of a POC, we worked to setup a small docker-compose file that can create a quick master-replica setup. Please feel free to refer to this for your own workloads :

```
version: '3'

services:
  kvrocks-master-1:
    container_name: 'kvrocks-master-1'
    image: apache/kvrocks:nightly
    ports: 
      - 6667:6666
  kvrocks-replica-1:
    container_name: 'kvrocks-replica-1'
    image: apache/kvrocks:nightly
    ports:
      - 6668:6666
    depends_on:
      - kvrocks-master-1
  redis-cli:
    container_name: redis-cli
    image: redis
    depends_on:
      - kvrocks-master-1
      - kvrocks-replica-1
    entrypoint: ["redis-cli"]
    command: ["-h", "kvrocks-replica-1", "-p", "6666", "slaveof" ,"kvrocks-master-1", "6666"]
```

PS, this is easily extendible for redis-sentinel monitoring and failover use cases as well :D
