### DISCUSSION TITLE
Add PVC to Kvrocks POD in k8s

### DISCUSSION THREAD

**Discussion by chethankumar4046** [apache/kvrocks#1620] [General]
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: kvrocks-data-path-pvc
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    storageClassName: topolvm-provisioner
    volumeMode: Filesystem
---
apiVersion: v1
kind: Secret
metadata:
    name: cache-secret
immutable: false
stringData:
    REDIS_PASSWORD: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: cache-new
    name: cache-new
spec:
    replicas: 1
    selector:
        matchLabels:
            app: cache-new
    serviceName: cache-new-service
    template:
        metadata:
            labels:
                app: cache-new
        spec:
            containers:
                - args:
                      - --requirepass
                      - $(REDIS_PASSWORD)
                      - --port
                      - '6379'
                  env:
                      - name: REDIS_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                key: REDIS_PASSWORD
                                name: cache-secret
                  image: apache/kvrocks
                  imagePullPolicy: Always
                  name: cache-new
                  ports:
                      - containerPort: 6379
                        protocol: TCP
                  volumeMounts:
                      - mountPath: /var/lib/kvrocks
                        name: kvrocks-data
            imagePullSecrets:
                - name: registrycred
            initContainers:
                - command:
                      - sh
                      - -c
                      - if [ -z "$(ls -A /var/lib/kvrocks)" ]; then cp -r /var/lib/kvrocks/* /data/; fi
                  image: apache/kvrocks
                  name: kvrocks-data
                  volumeMounts:
                      - mountPath: /data
                        name: kvrocks-data
            volumes:
                - name: kvrocks-data
                  persistentVolumeClaim:
                      claimName: kvrocks-data-path-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: cache-new
spec:
    ports:
        - name: redis
          port: 6379
          targetPort: 6379
    selector:
        app: cache-new
    type: ClusterIP

```
