### DISCUSSION TITLE
Whether Kvrocks can pass configurations through the command arguments or environments

### DISCUSSION THREAD

**Discussion by usrtax** [apache/kvrocks#848] [Q&A] [answered]
请问kvrocks是否支持通过命令行配置密码、端口、日志目录等参数？
如果不支持，就需要动态生成配置文件，感觉配合docker用比较麻烦

比如我redis的docker-compose.yml 是这么写的（可以在command直接通过环境变量设置，很方便）

```
version: '3'

services:
  redis-log:
    image: redis:7
    restart: 'no'
    volumes:
      - /var/log/docker/api.user.tax/redis:/log
    entrypoint: chown -R redis:redis /log
  redis:
    image: redis:7
    restart: always
    depends_on:
      - redis-log
    volumes:
      - ./data/redis:/data
      - /var/log/docker/api.user.tax/redis:/log
    command: --port ${REDIS_PORT} --requirepass ${REDIS_PASSWORD} --logfile /log/redis.log
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  ```
