### ISSUE TITLE
kvrocks does not start when customised kvrocks.conf is used

### ISSUE THREAD

**Issue by alija83** [apache/kvrocks#2364]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Version

Docker Compose version v2.15.1
kvrocks version 2.8.0.

### Minimal reproduce step

when using the following docker-compose configs
```
  kvrocks:
    image: apache/kvrocks:latest
    ports:
      - "6366:6366"
    volumes:
      - ./kvrocks/conf/kvrocks.conf:/etc/kvrocks/conf/kvrocks.conf
    entrypoint: ["kvrocks", "-c", "/etc/kvrocks/conf/kvrocks.conf"]
```
    
 and the kvrocks.conf file:
 ```
 dir /tmp/kvrocks

# General
#daemonize yes
port 6366
bind 0.0.0.0
```
   

### What did you expect to see?

I expected the service to start...normally and I am able to connect with redis-cli -p 6366

### What did you see instead?

 ⠿ Container microservices-kvrocks-1  Created                                                                                                                                                                                     0.0s
Attaching to microservices-kvrocks-1
microservices-kvrocks-1  | E20240614 15:41:22.642987     1 main.cc:180] Failed to start server: rename file encounter error: Resource busy

### Anything Else?

A quick solution is to mount the directory which contains the configuration file as follows:

```
    volumes:
      - ./kvrocks/conf:/etc/kvrocks/conf
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
