### ISSUE TITLE
Cancel previous CI workflow if new commit pushed

### ISSUE THREAD

**Issue by tisonkun** [apache/kvrocks#664]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

So that we don't waste time to verify a previous commit - what we're interested in is the latest view.

### Solution

Add the following snippet to `kvrocks.yaml`:

```yaml
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
```

See also https://github.com/apache/pulsar/blob/b23689930e3af65cfc913e2890164a071acda440/.github/workflows/pulsar-ci.yaml#L29-L31.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
