### ISSUE TITLE
Add more linux distro environments in GitHub Actions

### ISSUE THREAD

**Issue by PragmaTwice** [apache/kvrocks#795]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-kvrocks/issues) and found no similar issues.

### Motivation

As in https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container, we can use `jobs.<job_id>.container` to make all steps run on a specific docker image, like `centos` or others.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by tisonkun** [comment]
@PragmaTwice the issue here is what distros are supported on GitHub Actions (public).

**Comment by PragmaTwice** [comment]
> @PragmaTwice the issue here is what distros are supported on GitHub Actions (public).

I think we can use images in docker hub, e.g.
```yaml
jobs:
  build:
    runs-on: ubuntu:latest
    container: centos:7 # `centos:7` image from docker hub
    steps:
      ... # commands running on centos docker container
```
